
const types  = {
  SET_REPACKS: 'SET_REPACKS',
  SET_REPACK: 'SET_REPACK',
  AUTH_USER: 'AUTH_USER',
  SET_SEARCH_MODE: 'SET_SEARCH_MODE',
  SET_ACTION_RESULT: 'SET_ACTION_RESULT'
}

export default types